services:
  db:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 1s
      timeout: 1s
      retries: 10
  
  migrator:
    build:
      context: .
      dockerfile: OnlineShop.Migrations/Dockerfile
    env_file:
      - ./OnlineShop.Migrations/.env
    depends_on:
      db:
        condition: service_healthy
    command: [
      "${POSTGRES_HOST}",
      "${POSTGRES_PORT}",
      "${POSTGRES_DB}",
      "${POSTGRES_USER}",
      "${POSTGRES_PASSWORD}",
    ]

  api:
    build:
      context: . 
      dockerfile: OnlineShop.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./OnlineShop.Api/appsettings.Development.json:/app/appsettings.Development.json:ro
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "5000:8080"

  category_cleanup_worker:
    build:
      context: .
      dockerfile: OnlineShop.CategoryCleanup/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./OnlineShop.CategoryCleanup/appsettings.Development.json:/app/appsettings.Development.json:ro
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
