services:
  db:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 2s
      timeout: 2s
      retries: 10
      
  
  migrator:
    build:
      context: .
      dockerfile: OnlineShop.Migrations/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .  
      dockerfile: OnlineShop.Api/Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "5000:8080"


volumes:
  pg_data:
